### PR TITLE
Assert expected data when processing expectations

### PR DESCRIPTION
**Pull request by CryptidVulpes**
Expectations can be given "expected data" but nothing is done to that field when the expectations are processed.

This PR adds this functionality.

### CODE REVIEW

**Comment by CryptidVulpes** [comment]
@tarttelin Can you review this?

**Comment by tarttelin** [comment]
Was on holiday when you sent the pull request and then forgot about it. Will take a look now.

**Comment by tarttelin** [comment]
Sorry, these changes break Python 3 compatibility. I don't have time at the moment to fix it but if you are able to make the tests pass under both python 2 and 3, then I'll have another look.

**Comment by CryptidVulpes** [comment]
I'll fix the errors. I'll also add Python 3 tests to .travis.yml

**Comment by CryptidVulpes** [comment]
I created conflicts, sorry about that. I enabled Python 3.2, 3.3, 3.4 and 3.5

**Comment by tarttelin** [comment]
Manually merged. Thanks for the contribution, it's much appreciated!

**Pull request closed without merging**
